const data = {
  tutHtmlCss: [
    'HTML',
    'CSS',
    'Bootstrap',
    'Colors',
    'Icons',
    'Graphics',
    'SVG',
    'Canvas',
    'Sass',
  ],
  tutJs: ['Javascript', 'jQuery', 'React', 'AngularJS', 'JSON', 'AJAX', 'Vue'],
  tutProg: [
    'Python',
    'Java',
    'C',
    'C++',
    'C#',
    'R',
    'Kotlin',
    'Go',
    'Django',
    'Typescript',
  ],
  tutServerSide: [
    'SQL',
    'MySQL',
    'PHP',
    'ASP',
    'NodeJS',
    'MongoDB',
    'Git',
    'AWS',
    'Azure',
  ],
  tutWebBuilding: [
    'Create a Website',
    'Where to Start',
    'Web Templates',
    'Web Statistics',
    'Web Certificates',
    'Web Development',
    'Code Editor',
    'Cyber Security',
    'Accessibility',
  ],
  tutAnalytics: [
    'AI',
    'Machine Leaning',
    'Data Science',
    'NumPy',
    'Pandas',
    'SciPy',
    'Statistics',
    'Excel',
    'Google Sheets',
  ],
  tutXML: [
    'XML',
    'XML AJAX',
    'XML DOM',
    'XML DTD',
    'XML DTD',
    'XML Schema',
    'XSLT',
    'XPath',
    'XQuery',
  ],
  refHtml: ['Tag', 'Event', 'Color', 'Attribute', 'Canvas', 'SVG', 'Maps'],
  refCss: ['CSS', 'CSS Selector', 'Bootstrap 3', 'Bootstrap 4', 'Icon', 'Sass'],
  refJs: ['Javascript', 'HTML DOM', 'jQuery', 'AngularJS', 'AppML'],
  refProg: ['Python', 'Java'],
  refServerSide: ['SQL', 'MySQL', 'PHP', 'ASP'],
  refXML: ['DOM', 'Http', 'Schema'],
  refCharset: [
    'Character Sets',
    'ASCII',
    'ANSI',
    'Windows-1252',
    'ISO-8859-1',
    'Symbols',
    'UTF-8',
  ],
  exEx: [
    'HTML',
    'CSS',
    'Javascript',
    'Python',
    'SQL',
    'PHP',
    'Java',
    'C',
    'C++',
    'R',
    'Kotlin',
    'SciPy',
    'Excel',
    'Go',
    'Django',
    'Typescript',
    'MongoDB',
  ],
  exQuiz: [
    'HTML',
    'CSS',
    'Javascript',
    'Python',
    'SQL',
    'PHP',
    'Java',
    'C',
    'C++',
    'R',
    'Kotlin',
    'SciPy',
    'Excel',
    'Go',
    'Django',
    'Accessibility',
    'Cyber Security',
  ],
  exCourse: [
    'HTML',
    'CSS',
    'Javascript',
    'Python',
    'PHP',
    'Java',
    'C',
    'C++',
    'R',
    'Kotlin',
    'SciPy',
    'Excel',
    'Go',
    'Django',
    'Typescript',
    'MongoDB',
  ],
  exCert: [
    'HTML',
    'CSS',
    'Javascript',
    'Python',
    'PHP',
    'Java',
    'C',
    'C++',
    'R',
    'Kotlin',
    'Excel',
    'Go',
    'Django',
    'Typescript',
    'MongoDB',
  ],
};

module.exports = data;
